name: SduElectricityReminder

on:
  watch:
    types: [started]
  schedule:
    - cron: '0 9 * * *' # GMT+8 17:00

jobs:
  sdu-electricity-spider:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Spider in VPN
        uses: zhangt2333/actions-easyconnect@main
        with:
          CLI_OPTS: ${{ secrets.CLI_OPTS }}
          # 先通链路再运行脚本
          SCRIPT: |
            curl -m 5 --retry 5 -s -o /dev/null http://10.100.1.24:8988/web/Common/Tsm.html
            python Electricity-Spider/main.py "${{ secrets.DATA }}"